from .lemur import Lemur
from .wallaby import Wallaby
from .deer import Deer
from .chipmunk import Chipmunk
from .hedgehog import Hedgehog
from .chinchilla import Chinchilla
from .goat import Goat
from .alpaca import Alpaca
from .llama import Llama
from .snake import Snake
from .lizard import Lizard
from .turtle import Turtle
from .parrot import Parrot
from .macaw import Macaw
from .kookaburra import Kookaburra
